apiVersion: batch/v1
kind: CronJob
metadata:
  name: tmdb-weekly-releases
  namespace: cinekube
spec:
  # Run weekly on Mondays at 12:00 PM
  schedule: "0 12 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tmdb-weekly-releases
            image: cinekube/tmdb-weekly-releases:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: DATA_DIR
              value: "/data"
            - name: TMDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tmdb-secret
                  key: TMDB_API_KEY
            volumeMounts:
            - name: data-volume
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: data-pvc
