apiVersion: batch/v1
kind: CronJob
metadata:
  name: tmdb-monitor
  namespace: cinekube
spec:
  # Run every 6 hours
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tmdb-monitor
            image: cinekube/tmdb-monitor:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: DATA_DIR
              value: "/data"
            - name: TMDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tmdb-secret
                  key: TMDB_API_KEY
            volumeMounts:
            - name: data-volume
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: data-pvc
