apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cinekube-pvc
  namespace: cinekube-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # À ajuster selon tes besoins

