apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: cinekube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  # If running standard k3s, the default storage class is usually 'local-path'.
  # If you have a different default, or need to specify it, uncomment and change the line below:
  # storageClassName: local-path
